config/routes.rb
require 'ruby_event_store/browser/app'

Rails.application.routes.draw do
  root to: 'orders#index'
  resources :orders, only: [:index, :show, :new, :create, :destroy] do
    get  :pay
    post :ship
  end
  resources :payments, only: [:create]

  resources :customers, only: [:index, :show, :new, :edit, :create, :update]
  resources :products

  mount RubyEventStore::Browser::App => '/res' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def command_bus
    Rails.configuration.command_bus
  end

  def event_store
    Rails.application.config.event_store
  end

  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Orders::Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Orders::Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Orders::Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_path(@customer), notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_path(@customer), notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Orders::Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = OrderList::Order.all
  end

  def show
    order = OrderList::Order.find(params[:id])
    order_history = event_store.read.stream("Order$#{order.number}").backward.to_a
    payment_history = event_store.read.stream("OrderPayment$#{order.number}").backward.to_a
    @history = (order_history + payment_history).sort_by{|x| x.metadata[:timestamp]}.reverse
  end

  def new
    @products  = Orders::Product.all
    @customers = Orders::Customer.all
  end

  def create
    cmd = Orders::SubmitOrderCommand.new(
      items: order_items,
      customer_id: params[:customer_id])
    service.call(cmd)
    redirect_to orders_url, notice: 'Your order was submitted.'
  rescue Orders::Order::Invalid
    redirect_to orders_url, notice: "Could not submit the order, didn't you forget to add anything?"
  rescue Orders::Order::NotAllowed
    redirect_to orders_url, notice: "Could not submit the order."
  end

  def destroy
    order = OrderList::Order.find(params[:id])
    cmd = Orders::CancelOrderCommand.new(order_number: order.number)
    service.call(cmd)
    redirect_to orders_url, notice: 'Order was cancelled.'
  rescue Orders::Order::NotAllowed
    redirect_to orders_url, notice: "Could not cancel the order."
  end

  def pay
    @order = OrderList::Order.find(params[:order_id])
  end

  def ship
    order = OrderList::Order.find(params[:order_id])
    cmd = Orders::ShipOrderCommand.new(order_number: order.number)
    service.call(cmd)
    redirect_to orders_url, notice: 'Order shipment was initiated.'
  rescue Orders::Order::NotAllowed
    redirect_to orders_url, notice: "Could not ship the order."
  end

  private
  def service
    OrdersService.new(store: event_store,
                      pricing: ->(sku) { p = Orders::Product.find(sku); {net_price: p.net_price, vat_rate: p.vat_rate} })
  end

  def order_items
    params[:quantity].map(&:to_i).map.with_index { |quantity,index|
      {sku: params[:products][index], quantity: quantity} if quantity > 0
    }.compact
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    order = OrderList::Order.find_by(number: params[:order_number])
    cmd = Payments::AuthorizePaymentCommand.new(
      order_number: order.number,
      total_amount: order.gross_value,
      card_number:  params[:card_number])
    command_bus.call(cmd)
    redirect_to orders_url, notice: 'Order paid.'
  rescue
    redirect_to orders_url, notice: "Payment failed"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Orders::Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Orders::Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Orders::Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Orders::Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :net_price, :vat_rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_form.html.erb
<% if customer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

    <ul>
    <% customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="actions">
  <%= f.submit nil, class: 'btn btn-primary' %>
</div>

app/views/customers/edit.html.erb
<% provide(:title, 'Edit customer') %>
<h1>Editing Customer</h1>

<%= form_for(@customer, url: customer_path(@customer), as: :customer) do |f| %>
  <%= render 'form', customer: @customer, f: f %>
<% end %>
<%= link_to 'Back', customers_path, class: 'btn btn-default' %>

app/views/customers/index.html.erb
<% provide(:title, 'Customers list') %>
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= link_to 'Show', customer_path(customer), class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path, class: 'btn btn-default' %>

app/views/customers/new.html.erb
<% provide(:title, 'New customer') %>
<h1>New Customer</h1>

<%= form_for(@customer, url: customers_path, as: :customer) do |f| %>
  <%= render 'form', customer: @customer, f: f %>
<% end %>

<%= link_to 'Back', customers_path, class: 'btn btn-default' %>

app/views/customers/show.html.erb
<% provide(:title, 'New customer') %>
<div class="center">
  <p id="notice"><%= notice %></p>

  <p>
  <strong>Name:</strong>
  <%= @customer.name %>
  </p>

  <%= link_to 'Edit', edit_customer_path(@customer), class: 'btn btn-default' %>
  <%= link_to 'Back', customers_path, class: 'btn btn-default' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "CQRS/ES Sample App", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Your orders",   root_path %></li>
            <li><%= link_to "Products",    products_path %></li>
            <li><%= link_to "Customers",   customers_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<% provide(:title, 'Your orders') %>
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class="table">
  <thead>
    <tr>
      <th>Number</th>
      <th>Items count</th>
      <th>Net value</th>
      <th>Vat amount</th>
      <th>Gross value</th>
      <th>Customer name</th>
      <th>State</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.number %></td>
        <td><%= order.items_count %></td>
        <td><%= order.net_value %></td>
        <td><%= order.vat_amount %></td>
        <td><%= order.gross_value %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Pay', order_pay_path(order), class: 'btn btn-default' %></td>
        <td><%= link_to 'Ship', order_ship_path(order), method: :post, class: 'btn btn-default' %></td>
        <td><%= link_to 'Cancel', order_path(order), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
        <td><%= link_to 'History', order_path(order), class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path, class: 'btn btn-default' %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_tag({controller: "orders", action: "create"}, method: "post") do %>
<table class="table">
  <thead>
    <tr>
      <th>Product</th>
      <th>Net price</th>
      <th>Quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.net_price %></td>
        <td><%= number_field_tag "quantity[]", 0,  min: 0, step: 1 %>
            <%= hidden_field_tag "products[]", product.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <p>Customer:
  <%= select_tag(:customer_id, options_from_collection_for_select(@customers, :id, :name)) %>
  </p>

  <%= submit_tag("Submit order", class: "btn btn-primary") %>
  <%= link_to 'Back', orders_path, class: "btn btn-default" %>
<% end %>

app/views/orders/pay.html.erb
<h1>Payment for <%= @order.number %> </h1>

<%= form_tag({controller: "payments", action: "create"}, method: "post") do %>
  <%= hidden_field_tag "order_number", @order.number %></td>
  <p>Card number:
    <%= text_field_tag "card_number" %>
  </p>

  <%= submit_tag("Pay", class: "btn btn-primary") %>
  <%= link_to 'Back', orders_path, class: "btn btn-default" %>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tbody>
    <% @history.each do |event| %>
      <tr>
        <td colspan="4"><h4><%= event.class %></h4></td>
      </tr>
      <tr>
        <td><strong>ID:</strong></td>
        <td><%= event.event_id %></td>
        <td><strong>Timestamp:</strong></td>
        <td><%= event.timestamp %></td>
      </tr>
      <tr>
        <td><strong>Data:</strong></td>
        <td colspan="3">
          <table class='table'>
            <% event.data.to_h.each do |k,v| %>
              <tr>
                <td><%= k %>:</td>
                <td><%= v.to_s %></td>
              </tr>
            <% end %>
          </table>
        </td>
      </tr>
      <tr>
        <td><strong>Meta:</strong></td>
        <td colspan="3">
          <table class='table'>
            <% event.metadata.to_h.each do |k,v| %>
              <tr>
                <td><%= k %>:</td>
                <td><%= v.to_s %></td>
              </tr>
            <% end %>
          </table>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', orders_path, class: 'btn btn-default' %>

app/views/products/_form.html.erb
<% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :net_price %>
  <%= f.text_field :net_price %>
</div>

<div class="field">
  <%= f.label :vat_rate %>
  <%= f.number_field :vat_rate %>
</div>

<div class="actions">
  <%= f.submit nil, class: 'btn btn-primary' %>
</div>

app/views/products/edit.html.erb
<% provide(:title, 'Edit product') %>
<h1>Editing Product</h1>

<%= form_for(@product, url: product_path(@product), as: :product) do |f| %>
  <%= render 'form', product: @product, f: f %>
<% end %>

<%= link_to 'Back', products_path, class: 'btn btn-default' %>

app/views/products/index.html.erb
<% provide(:title, 'Products list') %>
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Net price</th>
      <th>Vat rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.net_price %></td>
        <td><%= product.vat_rate %></td>
        <td><%= link_to 'Show', product_path(product), class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', product_path(product), class: 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class: 'btn btn-default' %>

app/views/products/new.html.erb
<% provide(:title, 'New product') %>
<h1>New Product</h1>

<%= form_for(@product, url: products_path, as: :product) do |f| %>
  <%= render 'form', product: @product, f: f %>
<% end %>

<%= link_to 'Back', products_path, class: 'btn btn-default' %>

app/views/products/show.html.erb
<div class="center">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>

  <p>
    <strong>Net price:</strong>
    <%= @product.net_price %>
  </p>

  <p>
    <strong>Vat rate:</strong>
    <%= @product.vat_rate %>
  </p>

  <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-default' %>
  <%= link_to 'Back', products_path, class: 'btn btn-default' %>
</div>